# 3rd Meeting Exercise

1. Create a one-dimensional array from a list comprehension that produces the even integers from 2 through 20.

In [10]:
import numpy as np

In [11]:
np.arange(2, 22, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

2. Create a 2-by-5 array containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.

In [12]:
np.array([np.arange(2, 12, 2), np.arange(1, 10, 2)])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

3. Use NumPy function arange to create an array of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 array.

In [13]:
np.arange(2, 42, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

4. Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100, then reshape the result into a 3-by-4 array. Calculate the average of all the grades, the averages of the grades in each column and the averages of the grades in each row

In [14]:
import random
num4 = np.array([random.randrange(60, 100) for i in range(1, 13)]).reshape(3, 4)
print("Original Array", num4)
for i, value in enumerate(num4.mean(axis=0)):
    print("Average column ", i," is ", value)
for i, value in enumerate(num4.mean(axis=1)):
    print("Average row ", i," is ", value)

Original Array [[84 66 83 79]
 [92 89 67 86]
 [78 94 73 74]]
Average column  0  is  84.66666666666667
Average column  1  is  83.0
Average column  2  is  74.33333333333333
Average column  3  is  79.66666666666667
Average row  0  is  78.0
Average row  1  is  83.5
Average row  2  is  79.75


5. Given the following array:
>> array([[ 1, 2, 3, 4, 5],
>> [ 6, 7, 8, 9, 10],
>> [11, 12, 13, 14, 15]])

>> write statements to perform the following tasks:
>> 1. Select the second row.
>> 2. Select the first and third rows.
>> 3. Select the middle three columns.

In [15]:
num5 = np.array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

In [16]:
num5_1 = num5[1]
print("Second row is", num5_1)

Second row is [ 6  7  8  9 10]


In [17]:
num5_2 = num5[0::2]
print("First and third rows", num5_2)

First and third rows [[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [18]:
num5_3 = num5[:, 1:4]
print("Middle three columns", num5_3)

Middle three columns [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
